### ISSUE TITLE
scrolling in creative menu is broken with some config values

### ISSUE THREAD

**Issue by Taccnien** [SmajloSlovakian/Minecraft-Smooth-Scrolling#3]
Setting "creativeScreenSpeed" in config to certain values makes the animation not work.
When scrolling, the list of items is static. Sometimes, when the scrolling passes 1/2, it switches witout animation to other rows of items, also static.
Values found that make the bug manifest:
1.0
0.5

Another related bug:
when clicking on another tab in the creative menu for the first time, the scrolling animation plays once.

This happens even with only this mod installed, so no interference
minecraft 1.20.1

**Comment by SmajloSlovakian** [comment]
on all settings, there are safe and unsafe values... safe values are 0 and >1... the value 1 makes scrolling not work at all (for hotbar only visually) and other values just break things... i don't want people not to have the ability to use these just for fun... i will probably make a value, which will just act like a comment and tell those people that those values aren't safe...

for the creative menu changing tabs: if you change tabs, the target scroll position will be set to 0 but the actual scroll position will not, therefore the animation plays... i plan on fixing that in the next update

**Comment by SmajloSlovakian** [comment]
i have made a handful of changes to configs... it is now multiplicating instead of dividing and so the safe values are 0 - 1... i have made a thing in the code that will invert the values automatically (if they are not set to 0) when updating the mod and i have also made a comment inside the json file so people can read how to set those values...

the creative menu current scroll now resets when changing tabs or screens

fixed in 1.6.0
