### ISSUE TITLE
Wrong depends :) get some coffee mate

### ISSUE THREAD

**Issue by Psychodeus** [SmajloSlovakian/Minecraft-Smooth-Scrolling#54]
[Here in modrinth](https://modrinth.com/mod/smooth-scroll/versions?g=1.21.1) you said version mc 1.21.x
You wrote the wrong minecraft version in the json.

```
"depends": {
		"fabricloader": ">=0.14.21",
		"minecraft": "=1.20.1",
		"java": ">=17"
	},
```

**Comment by SmajloSlovakian** [comment]
cannot reproduce... the 1.21 version of the mod has dependency set as >1.20.6 in code... only the 1.20.1 branch has =1.20.1...

when i download the first version which appears when clicking your link and opening it in 7zip, it has >1.20.6 in it as a dependency...
the only issue here is that i have it set to future versions as well even if i don't really know if they will be compatible but that's by design as i don't want to force players to redownload the same thing when new minecraft version releases in case it is compatible

**Comment by SmajloSlovakian** [comment]
closing issue due to not being able to reproduce and no response... if you have any more information, just comment it here
