### ISSUE TITLE
Scrolling speed is slow

### ISSUE THREAD

**Issue by arcade-smasher** [SmajloSlovakian/Minecraft-Smooth-Scrolling#61]
I noticed the scrolling speed on some GUIs is a bit slower than I'd prefer. Not the scrolling animation, but the speed. A better way to put it would be **the distance scrolled when moving the scroll wheel up or dow**n. It seems to be slower than scrolling in vanilla, and if it's not, it just appears as so because of the animation. It would be nice if there could be a way to change to actual scrolling distance so I don't just resort to using the scrollbar every time.

**Comment by SmajloSlovakian** [comment]
there is a setting for that...
the vanilla way of doing the scrolling speed on entry lists (world select, server select screens) is that one scroll scrolls half the height of an element on the screen... i have changed that behaviour by default in this mod because i also didn't like it and i changed it to be a fixed amount of pixels (scaled with gui scale) and to be a bit faster than vanilla's world selection screen's (about 30 px per scroll)
you can change the scroll amount in the settings screen of the mod by going into modmenu and clicking on settings for my mod... alternatively you can go to .minecraft/config/smoothscroll.json and change the value there... i plan to make the scroll amount changable for everything like chat or creative screen too but that will be in a while...

i'm closing this issue but you can still ask here for help or give more information
